(cl:defpackage r2_msgs-msg
  (:use )
  (:export
   "<GAINS>"
   "GAINS"
   "<JOINTCONTROL>"
   "JOINTCONTROL"
   "<JOINTSTATUS>"
   "JOINTSTATUS"
   "<JOINTSTATUSARRAY>"
   "JOINTSTATUSARRAY"
   "<PDMCSTATUS>"
   "PDMCSTATUS"
   "<POSECOMMAND>"
   "POSECOMMAND"
   "<POSECOMMANDARRAY>"
   "POSECOMMANDARRAY"
   "<POSECOMMANDPARAMS>"
   "POSECOMMANDPARAMS"
   "<POSECOMMANDSTATUS>"
   "POSECOMMANDSTATUS"
   "<POSETWISTSTAMPED>"
   "POSETWISTSTAMPED"
   "<TORSOSTATUS>"
   "TORSOSTATUS"
  ))

