// Generated by gencpp from file basic/WordCount.msg
// DO NOT EDIT!


#ifndef BASIC_MESSAGE_WORDCOUNT_H
#define BASIC_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <basic/WordCountRequest.h>
#include <basic/WordCountResponse.h>


namespace basic
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace basic


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::basic::WordCount > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::basic::WordCount&) { return value(); }
};

template<>
struct DataType< ::basic::WordCount > {
  static const char* value()
  {
    return "basic/WordCount";
  }

  static const char* value(const ::basic::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::basic::WordCountRequest> should match 
// service_traits::MD5Sum< ::basic::WordCount > 
template<>
struct MD5Sum< ::basic::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::basic::WordCount >::value();
  }
  static const char* value(const ::basic::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::basic::WordCountRequest> should match 
// service_traits::DataType< ::basic::WordCount > 
template<>
struct DataType< ::basic::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::basic::WordCount >::value();
  }
  static const char* value(const ::basic::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::basic::WordCountResponse> should match 
// service_traits::MD5Sum< ::basic::WordCount > 
template<>
struct MD5Sum< ::basic::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::basic::WordCount >::value();
  }
  static const char* value(const ::basic::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::basic::WordCountResponse> should match 
// service_traits::DataType< ::basic::WordCount > 
template<>
struct DataType< ::basic::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::basic::WordCount >::value();
  }
  static const char* value(const ::basic::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASIC_MESSAGE_WORDCOUNT_H
